<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>location_Catagory</name>
   <tag></tag>
   <elementGuidId>5e665e79-fdf4-4d5a-9820-b5c4c7083c0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/r4-root/section/div/r4-querybuilder/div/div/div[2]/r4-query-concept-editor/div/form/div[2]/div/div[1]/div/div[1]/div/p-tree/div/ul/p-treenode[1]/li/div/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-treenode-content ui-treenode-selectable</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-klass</name>
      <type>Main</type>
      <value>ui-treenode-content</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>City</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/r4-root[@class=&quot;ng-tns-c0-0&quot;]/section[@class=&quot;content ng-tns-c0-0 ng-star-inserted&quot;]/div[@class=&quot;content-outlet&quot;]/r4-querybuilder[@class=&quot;ng-tns-c17-21 ng-star-inserted&quot;]/div[@class=&quot;query-content&quot;]/div[@class=&quot;query-builder&quot;]/div[@class=&quot;query-builder--content-editor&quot;]/r4-query-concept-editor[@class=&quot;ng-tns-c17-21 ng-trigger ng-trigger-enterAnimation ng-star-inserted&quot;]/div[@class=&quot;query-concept-editor&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;query-concept-editor--row&quot;]/div[@class=&quot;query-concept-editor--content&quot;]/div[@class=&quot;query-concept-editor--content--search&quot;]/div[@class=&quot;query-concept-editor--browse&quot;]/div[@class=&quot;query-concept-editor--content--categories ng-star-inserted&quot;]/div[@class=&quot;categories-browse&quot;]/p-tree[1]/div[@class=&quot;ui-tree ui-widget ui-widget-content ui-corner-all ui-tree-selectable ng-star-inserted&quot;]/ul[@class=&quot;ui-tree-container ng-star-inserted&quot;]/p-treenode[@class=&quot;ng-star-inserted&quot;]/li[@class=&quot;ui-treenode ng-star-inserted&quot;]/ul[@class=&quot;ui-treenode-children ng-star-inserted&quot;]/p-treenode[@class=&quot;ng-star-inserted&quot;]/li[@class=&quot;ui-treenode ui-treenode-leaf ng-star-inserted&quot;]/div[@class=&quot;ui-treenode-content ui-treenode-selectable&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Geography'])[1]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browse Categories'])[1]/following::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Region'])[1]/preceding::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/p-treenode/li/div</value>
   </webElementXpaths>
</WebElementEntity>
